"""PowerPoint report generation for TelecomGPT."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

_OUTPUT_DIR = Path(__file__).resolve().parent.parent / "data" / "reports"


def _split_sections(content: str) -> list[tuple[str, str]]:
    """Split content into (title, body) slide sections."""
    sections: list[tuple[str, str]] = []
    blocks = re.split(r"\n(?=#{1,3}\s|\*\*[A-Z])", content.strip())
    for block in blocks:
        block = block.strip()
        if not block:
            continue
        lines = block.split("\n", 1)
        title = re.sub(r"^#+\s*|\*\*", "", lines[0]).strip()[:80]
        body = lines[1].strip() if len(lines) > 1 else block
        sections.append((title or "Overview", body[:1500]))
    if not sections:
        paragraphs = [p.strip() for p in content.split("\n\n") if p.strip()]
        for i, para in enumerate(paragraphs[:12]):
            sections.append((f"Section {i + 1}", para))
    return sections[:15]


def generate_presentation(
    *,
    topic: str,
    content: str,
    session_id: str = "default",
    subtitle: str = "TelecomGPT Report",
) -> dict:
    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    safe = re.sub(r"[^\w\-]+", "_", topic.lower())[:40].strip("_") or "report"
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"{safe}_{ts}.pptx"
    out_path = _OUTPUT_DIR / filename

    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
    except ImportError as e:
        return {
            "ok": False,
            "error": "python-pptx not installed. Run: pip install python-pptx",
            "path": None,
            "filename": None,
        }

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = topic[:100]
    if slide.placeholders:
        try:
            slide.placeholders[1].text = f"{subtitle}\n{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
        except (IndexError, KeyError):
            pass

    sections = _split_sections(content)
    if not sections:
        sections = [("Summary", content[:1500])]

    for title, body in sections:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = title
        tf = slide.placeholders[1].text_frame
        tf.clear()
        bullets = [ln.strip("-• ").strip() for ln in body.split("\n") if ln.strip()]
        if not bullets:
            bullets = [body[:500]]
        for i, bullet in enumerate(bullets[:8]):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            p.text = bullet[:300]
            p.level = 0
            p.font.size = Pt(18)

    # Closing slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Sources & Notes"
    tf = slide.placeholders[1].text_frame
    tf.text = "Generated by TelecomGPT multi-agent orchestrator.\nVerify against 3GPP specs and field measurements."

    prs.save(str(out_path))

    return {
        "ok": True,
        "path": str(out_path),
        "filename": filename,
        "session_id": session_id,
        "slides": len(sections) + 2,
        "download_url": f"/api/reports/{filename}",
    }
